# Site settings
title: Felinesoft Front-End Guidelines
email: kimberly.grey@felinesoft.co.uk
description: Made withï¸ ğŸ˜»ï¸ in Bristol.
baseurl: "/FSFrontEndDocs" # the subpath of your site, e.g. /blog/
url: "http://querkmachine.github.io" # the base hostname & protocol for your site
pemalink: /:title

# Build settings
destination: docs
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
